### ISSUE TITLE
Using subprocess macros

### ISSUE THREAD

**Issue by jnoortheen** [anki-code/xontrib-sh#1]
I just stumbled across this package. I don't know if this is possible. But here is an idea of using [subprocess macros](https://xon.sh/tutorial_macros.html#subprocess-macros) to identify the shell language. 

So something like 
```
bash! export var=12
zsh! export var=12
```
would become possible.

**Comment by anki-code** [comment]
Hi @jnoortheen! 
Yes you can do `bash -c! ls` to run the another shell command.

But there are two issues around this approach:

1. You can't paste the multiline piece of script::
```bash
bash -c! for i in 1 2 3
do
   echo $i
done
# Syntax error
```
```bash
! for i in 1 2 3
do
   echo $i
done

#1
#2
#3
```

2. You should write `bash -c!` command that has more keystrokes than just `! ` :)

**Comment by jnoortheen** [comment]
Yes thanks, I got here after checking out the ergopack. I currently don't have use for shell specific snippets, so a PR wouldn't be possible. Just wanted to see how this can be handled.
