### ISSUE TITLE
PowerShell hasn't syntax checking option

### ISSUE THREAD

**Issue by eugenesvk** [anki-code/xontrib-sh#3]
On Windows when including PowerShell 7 (`$XONTRIB_SH_SHELLS = ['pwsh']`) trying a `! echo 1` fails with 
```
pwsh:
Invalid argument '-nc', did you mean:
  -encodedcommand
```

I guess this is due to the fact that there is no `-n` flag in PowerShell, and I don't know what the alternative for noexec syntax check is
https://github.com/anki-code/xontrib-sh/blob/9c0d2deb9a9b7e5f76082d677cc9a400f11d7253/xontrib/sh.py#L22

**Comment by anki-code** [comment]
Hi! Thank you for reporting this!
To avoid this we can disable syntax checking when we have one shell in the list and just run the code.
PR is welcome!
