### ISSUE TITLE
Is there a way to make an alias that will be interpreted the same as manually entering this?

### ISSUE THREAD

**Issue by meramsey** [anki-code/xontrib-sh#6]
For example the only way I can use nvm in xonsh is with 

Doing this in terminal works fine
```
! [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && nvm ls
```

If i setup an alias to make it easier to do that it fails
```python
aliases['nvm'] = '! [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" && nvm'
# or like
aliases['nvm'] = '!bash [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" && nvm'
```

I get an error like this

<details>

```
@ nvm
Traceback (Most recent call last):
523 /home/mike/.pyenv/versions/3.9.6/lib/python3.9/site-packages/xonsh/parsers/base.py parse --> tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
335 /home/mike/.pyenv/versions/3.9.6/lib/python3.9/site-packages/xonsh/ply/ply/yacc.py parse --> return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
1203 /home/mike/.pyenv/versions/3.9.6/lib/python3.9/site-packages/xonsh/ply/ply/yacc.py parseopt_notrack --> tok = call_errorfunc(self.errorfunc, errtoken, self)
194 /home/mike/.pyenv/versions/3.9.6/lib/python3.9/site-packages/xonsh/ply/ply/yacc.py call_errorfunc --> r = errorfunc(token)
3459 /home/mike/.pyenv/versions/3.9.6/lib/python3.9/site-packages/xonsh/parsers/base.py p_error --> self._parse_error(msg, self.currloc(lineno=p.lineno, column=p.lexpos))
650 /home/mike/.pyenv/versions/3.9.6/lib/python3.9/site-packages/xonsh/parsers/base.py _parse_error --> raise_parse_error(msg, loc, self.xonsh_code, self.lines)
238 /home/mike/.pyenv/versions/3.9.6/lib/python3.9/site-packages/xonsh/parsers/base.py raise_parse_error --> raise err
SyntaxError: <exec-alias:nvm>:1:0: ('code: !',)
!bash [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" && nvm
^
~ [✖ ERROR] at 18:40:48
 
@
```

</details>

If i try to put all but the ! in the alias and then use ! nvm which is an alias for `[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" && nvm` it also doesn't like that I think as its being expanded in bash and skipping the xontrib loading.

Seems like I should be able to create an alias that calls it through the sh thing like doing it manually would, but I probably missed that option.

Any tips would be super appreciated. This plugin is what really ensured I didn't give up on xonsh. The convenience of being able to prefix is amazing. I'm just curious if there is a way to make an alias or callable that mimics me entering the ! at the beginning before its executed.

**Comment by anki-code** [comment]
hi @meramsey!
I'm not the user of `nvm` but I think this [`ExecAlias`](https://xon.sh/tutorial.html#aliases) will work:
```python
aliases['nvm'] = """bash -c @('[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" && nvm ' + ' '.join($args))"""
```

**Comment by meramsey** [comment]
wow you sir are genious and this works perfectly. This is what I love about xonsh is that possibilities are endless.

Thanks for taking the time to share with me. learned something new here.
